server:
  port: 10083

spring:
  data:
    rest:
      detection-strategy: explicit_method_annotated
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect

    hibernate:
      ddl-auto: ${DDL_AUTO:update}

  datasource:
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://${MYSQL_HOST:localhost}:${MYSQL_PORT:6603}/${MYSQL_DATABASE:autobots}?allowPublicKeyRetrieval=true&reconnect=true&verifyServerCertificate=false&useSSL=false
    username: ${MYSQL_USER:root}
    password: ${MYSQL_PASS:mysql}

  jackson:
    serialization:
      fail-on-empty-beans: false
      WRITE_DATES_AS_TIMESTAMPS: false

  rabbitmq:
    host: ${RABBITMQ_HOST:localhost}
    port: ${RABBITMQ_PORT:5672}
    username: ${RABBITMQ_USER:guest}
    password: ${RABBITMQ_PASS:guest}
